- name: Include setup tasks
  import_tasks: setup.yml
  tags:
    - svn
  when: not svn_server_remove

- name: Include remove tasks
  import_tasks: remove.yml
  tags:
    - svn
  when: svn_server_remove
